export interface DraftTemplate {
  id: string;
  name: string;
  description: string;
  fileName: string; // file under /public/drafts
}

export const DRAFT_TEMPLATES: DraftTemplate[] = [
  {
    id: "affidavit",
    name: "Affidavit",
    description: "General-purpose sworn affidavit template.",
    fileName: "affidavit.docx",
  },
  {
    id: "vakalatnama",
    name: "Vakalatnama",
    description: "Power of attorney appointing an advocate for a case.",
    fileName: "vakalatnama.docx",
  },
  {
    id: "legal-notice",
    name: "Legal Notice",
    description: "Formal notice letter to an opposing party.",
    fileName: "legal-notice.docx",
  },
  {
    id: "application-for-adjournment",
    name: "Application for Adjournment",
    description: "Request to the court to adjourn a scheduled hearing.",
    fileName: "application-for-adjournment.docx",
  },
  {
    id: "plaint-recovery",
    name: "Plaint for Recovery of Money",
    description: "Civil suit plaint seeking recovery of money from a defendant.",
    fileName: "01_Plaint_Recovery.docx",
  },
  {
    id: "plaint-declaration",
    name: "Plaint for Declaration",
    description: "Civil suit plaint seeking a declaratory decree from the court.",
    fileName: "02_Plaint_Declaration.docx",
  },
  {
    id: "application-section-151-cpc",
    name: "Application Section 151 CPC",
    description: "Court-ready template for a(n) application section 151 cpc.",
    fileName: "01_Application_Section_151_CPC.docx",
  },
  {
    id: "application-temporary-injunction-order-xxxix",
    name: "Application Temporary Injunction Order XXXIX",
    description: "Court-ready template for a(n) application temporary injunction order xxxix.",
    fileName: "02_Application_Temporary_Injunction_Order_XXXIX.docx",
  },
  {
    id: "plaint-permanent-injunction",
    name: "Plaint Permanent Injunction",
    description: "Court-ready template for a(n) plaint permanent injunction.",
    fileName: "03_Plaint_Permanent_Injunction.docx",
  },
  {
    id: "stay-application",
    name: "Stay Application",
    description: "Court-ready template for a(n) stay application.",
    fileName: "03_Stay_Application.docx",
  },
  {
    id: "amendment-of-plaint",
    name: "Amendment Of Plaint",
    description: "Court-ready template for a(n) amendment of plaint.",
    fileName: "04_Amendment_of_Plaint.docx",
  },
  {
    id: "plaint-mandatory-injunction",
    name: "Plaint Mandatory Injunction",
    description: "Court-ready template for a(n) plaint mandatory injunction.",
    fileName: "04_Plaint_Mandatory_Injunction.docx",
  },
  {
    id: "amendment-of-written-statement",
    name: "Amendment Of Written Statement",
    description: "Court-ready template for a(n) amendment of written statement.",
    fileName: "05_Amendment_of_Written_Statement.docx",
  },
  {
    id: "plaint-possession",
    name: "Plaint Possession",
    description: "Court-ready template for a(n) plaint possession.",
    fileName: "05_Plaint_Possession.docx",
  },
  {
    id: "plaint-specific-performance",
    name: "Plaint Specific Performance",
    description: "Court-ready template for a(n) plaint specific performance.",
    fileName: "06_Plaint_Specific_Performance.docx",
  },
  {
    id: "restoration-application",
    name: "Restoration Application",
    description: "Court-ready template for a(n) restoration application.",
    fileName: "06_Restoration_Application.docx",
  },
  {
    id: "impleadment-application",
    name: "Impleadment Application",
    description: "Court-ready template for a(n) impleadment application.",
    fileName: "07_Impleadment_Application.docx",
  },
  {
    id: "plaint-partition",
    name: "Plaint Partition",
    description: "Court-ready template for a(n) plaint partition.",
    fileName: "07_Plaint_Partition.docx",
  },
  {
    id: "deletion-of-party",
    name: "Deletion Of Party",
    description: "Court-ready template for a(n) deletion of party.",
    fileName: "08_Deletion_of_Party.docx",
  },
  {
    id: "plaint-damages",
    name: "Plaint Damages",
    description: "Court-ready template for a(n) plaint damages.",
    fileName: "08_Plaint_Damages.docx",
  },
  {
    id: "plaint-cancellation-of-document",
    name: "Plaint Cancellation Of Document",
    description: "Court-ready template for a(n) plaint cancellation of document.",
    fileName: "09_Plaint_Cancellation_of_Document.docx",
  },
  {
    id: "summoning-witness",
    name: "Summoning Witness",
    description: "Court-ready template for a(n) summoning witness.",
    fileName: "09_Summoning_Witness.docx",
  },
  {
    id: "production-of-documents",
    name: "Production Of Documents",
    description: "Court-ready template for a(n) production of documents.",
    fileName: "10_Production_of_Documents.docx",
  },
  {
    id: "written-statement",
    name: "Written Statement",
    description: "Court-ready template for a(n) written statement.",
    fileName: "10_Written_Statement.docx",
  },
  {
    id: "discovery-of-documents",
    name: "Discovery Of Documents",
    description: "Court-ready template for a(n) discovery of documents.",
    fileName: "11_Discovery_of_Documents.docx",
  },
  {
    id: "replication",
    name: "Replication",
    description: "Court-ready template for a(n) replication.",
    fileName: "11_Replication.docx",
  },
  {
    id: "application-section-151-cpc-2",
    name: "Application Section 151 CPC",
    description: "Court-ready template for a(n) application section 151 cpc.",
    fileName: "12_Application_Section_151_CPC.docx",
  },
  {
    id: "inspection-of-documents",
    name: "Inspection Of Documents",
    description: "Court-ready template for a(n) inspection of documents.",
    fileName: "12_Inspection_of_Documents.docx",
  },
  {
    id: "application-temporary-injunction",
    name: "Application Temporary Injunction",
    description: "Court-ready template for a(n) application temporary injunction.",
    fileName: "13_Application_Temporary_Injunction.docx",
  },
  {
    id: "local-commission",
    name: "Local Commission",
    description: "Court-ready template for a(n) local commission.",
    fileName: "13_Local_Commission.docx",
  },
  {
    id: "appointment-of-receiver",
    name: "Appointment Of Receiver",
    description: "Court-ready template for a(n) appointment of receiver.",
    fileName: "14_Appointment_of_Receiver.docx",
  },
  {
    id: "stay-application-2",
    name: "Stay Application",
    description: "Court-ready template for a(n) stay application.",
    fileName: "14_Stay_Application.docx",
  },
  {
    id: "application-amendment-of-plaint",
    name: "Application Amendment Of Plaint",
    description: "Court-ready template for a(n) application amendment of plaint.",
    fileName: "15_Application_Amendment_of_Plaint.docx",
  },
  {
    id: "condonation-of-delay",
    name: "Condonation Of Delay",
    description: "Court-ready template for a(n) condonation of delay.",
    fileName: "15_Condonation_of_Delay.docx",
  },
  {
    id: "application-restoration",
    name: "Application Restoration",
    description: "Court-ready template for a(n) application restoration.",
    fileName: "16_Application_Restoration.docx",
  },
  {
    id: "rejection-of-plaint",
    name: "Rejection Of Plaint",
    description: "Court-ready template for a(n) rejection of plaint.",
    fileName: "16_Rejection_of_Plaint.docx",
  },
  {
    id: "application-impleadment",
    name: "Application Impleadment",
    description: "Court-ready template for a(n) application impleadment.",
    fileName: "17_Application_Impleadment.docx",
  },
  {
    id: "return-of-plaint",
    name: "Return Of Plaint",
    description: "Court-ready template for a(n) return of plaint.",
    fileName: "17_Return_of_Plaint.docx",
  },
  {
    id: "application-summoning-witness",
    name: "Application Summoning Witness",
    description: "Court-ready template for a(n) application summoning witness.",
    fileName: "18_Application_Summoning_Witness.docx",
  },
  {
    id: "withdrawal-of-suit",
    name: "Withdrawal Of Suit",
    description: "Court-ready template for a(n) withdrawal of suit.",
    fileName: "18_Withdrawal_of_Suit.docx",
  },
  {
    id: "application-production-of-documents",
    name: "Application Production Of Documents",
    description: "Court-ready template for a(n) application production of documents.",
    fileName: "19_Application_Production_of_Documents.docx",
  },
  {
    id: "certified-copy-application",
    name: "Certified Copy Application",
    description: "Court-ready template for a(n) certified copy application.",
    fileName: "19_Certified_Copy_Application.docx",
  },
  {
    id: "application-local-commission",
    name: "Application Local Commission",
    description: "Court-ready template for a(n) application local commission.",
    fileName: "20_Application_Local_Commission.docx",
  },
  {
    id: "substitution-of-legal-heirs",
    name: "Substitution Of Legal Heirs",
    description: "Court-ready template for a(n) substitution of legal heirs.",
    fileName: "20_Substitution_of_Legal_Heirs.docx",
  },
  {
    id: "additional-evidence-application",
    name: "Additional Evidence Application",
    description: "Court-ready template for a(n) additional evidence application.",
    fileName: "21_Additional_Evidence_Application.docx",
  },
  {
    id: "application-for-acceptance-of-plea-bargain",
    name: "Application For Acceptance Of Plea Bargain",
    description: "Court-ready template for a(n) application for acceptance of plea bargain.",
    fileName: "APPLICATION FOR ACCEPTANCE OF PLEA BARGAIN.docx",
  },
  {
    id: "application-for-acquittal",
    name: "Application For Acquittal",
    description: "Court-ready template for a(n) application for acquittal.",
    fileName: "APPLICATION FOR ACQUITTAL.docx",
  },
  {
    id: "application-for-adjournment-2",
    name: "Application For Adjournment",
    description: "Court-ready template for a(n) application for adjournment.",
    fileName: "APPLICATION FOR ADJOURNMENT.docx",
  },
  {
    id: "application-for-attachment-of-bank-account",
    name: "Application For Attachment Of Bank Account",
    description: "Court-ready template for a(n) application for attachment of bank account.",
    fileName: "APPLICATION FOR ATTACHMENT OF BANK ACCOUNT.docx",
  },
  {
    id: "application-for-attachment-of-property",
    name: "Application For Attachment Of Property",
    description: "Court-ready template for a(n) application for attachment of property.",
    fileName: "APPLICATION FOR ATTACHMENT OF PROPERTY.docx",
  },
  {
    id: "application-for-bail-after-conviction",
    name: "Application For Bail After Conviction",
    description: "Court-ready template for a(n) application for bail after conviction.",
    fileName: "APPLICATION FOR BAIL AFTER CONVICTION.docx",
  },
  {
    id: "application-for-bail-for-juvenile",
    name: "Application For Bail For Juvenile",
    description: "Court-ready template for a(n) application for bail for juvenile.",
    fileName: "APPLICATION FOR BAIL FOR JUVENILE.docx",
  },
  {
    id: "application-for-bail-on-medical-grounds",
    name: "Application For Bail On Medical Grounds",
    description: "Court-ready template for a(n) application for bail on medical grounds.",
    fileName: "APPLICATION FOR BAIL ON MEDICAL GROUNDS.docx",
  },
  {
    id: "application-for-benefit-of-probation",
    name: "Application For Benefit Of Probation",
    description: "Court-ready template for a(n) application for benefit of probation.",
    fileName: "APPLICATION FOR BENEFIT OF PROBATION.docx",
  },
  {
    id: "application-for-cancellation-of-bail",
    name: "Application For Cancellation Of Bail",
    description: "Court-ready template for a(n) application for cancellation of bail.",
    fileName: "APPLICATION FOR CANCELLATION OF BAIL.docx",
  },
  {
    id: "application-for-certified-copy",
    name: "Application For Certified Copy",
    description: "Court-ready template for a(n) application for certified copy.",
    fileName: "APPLICATION FOR CERTIFIED COPY.docx",
  },
  {
    id: "application-for-discharge-of-accused",
    name: "Application For Discharge Of Accused",
    description: "Court-ready template for a(n) application for discharge of accused.",
    fileName: "APPLICATION FOR DISCHARGE OF ACCUSED.docx",
  },
  {
    id: "application-for-exemption-for-counsel",
    name: "Application For Exemption For Counsel",
    description: "Court-ready template for a(n) application for exemption for counsel.",
    fileName: "APPLICATION FOR EXEMPTION FOR COUNSEL.docx",
  },
  {
    id: "application-for-exemption-from-personal-appearance",
    name: "Application For Exemption From Personal Appearance",
    description: "Court-ready template for a(n) application for exemption from personal appearance.",
    fileName: "APPLICATION FOR EXEMPTION FROM PERSONAL APPEARANCE.docx",
  },
  {
    id: "application-for-interim-bail",
    name: "Application For Interim Bail",
    description: "Court-ready template for a(n) application for interim bail.",
    fileName: "APPLICATION FOR INTERIM BAIL.docx",
  },
  {
    id: "application-for-interim-relief-stay",
    name: "Application For Interim Relief - Stay",
    description: "Court-ready template for a(n) application for interim relief - stay.",
    fileName: "APPLICATION FOR INTERIM RELIEF - STAY.docx",
  },
  {
    id: "application-for-issuance-of-execution",
    name: "Application For Issuance Of Execution",
    description: "Court-ready template for a(n) application for issuance of execution.",
    fileName: "APPLICATION FOR ISSUANCE OF EXECUTION.docx",
  },
  {
    id: "application-for-post-arrest-bail",
    name: "Application For Post-arrest Bail",
    description: "Court-ready template for a(n) application for post-arrest bail.",
    fileName: "APPLICATION FOR POST-ARREST BAIL.docx",
  },
  {
    id: "application-for-pre-arrest-bail",
    name: "Application For Pre-arrest Bail",
    description: "Court-ready template for a(n) application for pre-arrest bail.",
    fileName: "APPLICATION FOR PRE-ARREST BAIL.docx",
  },
  {
    id: "application-for-protective-bail",
    name: "Application For Protective Bail",
    description: "Court-ready template for a(n) application for protective bail.",
    fileName: "APPLICATION FOR PROTECTIVE BAIL.docx",
  },
  {
    id: "application-for-recall-of-witness",
    name: "Application For Recall Of Witness",
    description: "Court-ready template for a(n) application for recall of witness.",
    fileName: "APPLICATION FOR RECALL OF WITNESS.docx",
  },
  {
    id: "application-for-recording-additional-evidence",
    name: "Application For Recording Additional Evidence",
    description: "Court-ready template for a(n) application for recording additional evidence.",
    fileName: "APPLICATION FOR RECORDING ADDITIONAL EVIDENCE.docx",
  },
  {
    id: "application-for-release-of-vehicle",
    name: "Application For Release Of Vehicle",
    description: "Court-ready template for a(n) application for release of vehicle.",
    fileName: "APPLICATION FOR RELEASE OF VEHICLE.docx",
  },
  {
    id: "application-for-restoration-of-criminal-complaint",
    name: "Application For Restoration Of Criminal Complaint",
    description: "Court-ready template for a(n) application for restoration of criminal complaint.",
    fileName: "APPLICATION FOR RESTORATION OF CRIMINAL COMPLAINT.docx",
  },
  {
    id: "application-for-return-of-property",
    name: "Application For Return Of Property",
    description: "Court-ready template for a(n) application for return of property.",
    fileName: "APPLICATION FOR RETURN OF PROPERTY.docx",
  },
  {
    id: "application-for-sale-of-attached-property",
    name: "Application For Sale Of Attached Property",
    description: "Court-ready template for a(n) application for sale of attached property.",
    fileName: "APPLICATION FOR SALE OF ATTACHED PROPERTY.docx",
  },
  {
    id: "application-for-summoning-of-witness",
    name: "Application For Summoning Of Witness",
    description: "Court-ready template for a(n) application for summoning of witness.",
    fileName: "APPLICATION FOR SUMMONING OF WITNESS.docx",
  },
  {
    id: "application-for-superdari",
    name: "Application For Superdari",
    description: "Court-ready template for a(n) application for superdari.",
    fileName: "APPLICATION FOR SUPERDARI.docx",
  },
  {
    id: "application-for-supply-of-challan-papers",
    name: "Application For Supply Of Challan Papers",
    description: "Court-ready template for a(n) application for supply of challan papers.",
    fileName: "APPLICATION FOR SUPPLY OF CHALLAN PAPERS.docx",
  },
  {
    id: "application-for-supply-of-documents",
    name: "Application For Supply Of Documents",
    description: "Court-ready template for a(n) application for supply of documents.",
    fileName: "APPLICATION FOR SUPPLY OF DOCUMENTS.docx",
  },
  {
    id: "application-for-suspension-of-sentence",
    name: "Application For Suspension Of Sentence",
    description: "Court-ready template for a(n) application for suspension of sentence.",
    fileName: "APPLICATION FOR SUSPENSION OF SENTENCE.docx",
  },
  {
    id: "application-for-transfer-of-criminal-case",
    name: "Application For Transfer Of Criminal Case",
    description: "Court-ready template for a(n) application for transfer of criminal case.",
    fileName: "APPLICATION FOR TRANSFER OF CRIMINAL CASE.docx",
  },
  {
    id: "application-for-urgent-hearing",
    name: "Application For Urgent Hearing",
    description: "Court-ready template for a(n) application for urgent hearing.",
    fileName: "APPLICATION FOR URGENT HEARING.docx",
  },
  {
    id: "application-under-section-249-a-cr-p-c",
    name: "Application Under Section 249-a Cr.P.C.",
    description: "Court-ready template for a(n) application under section 249-a cr.p.c..",
    fileName: "APPLICATION UNDER SECTION 249-A Cr.P.C..docx",
  },
  {
    id: "application-under-section-265-k-cr-p-c",
    name: "Application Under Section 265-k Cr.P.C.",
    description: "Court-ready template for a(n) application under section 265-k cr.p.c..",
    fileName: "APPLICATION UNDER SECTION 265-K Cr.P.C..docx",
  },
  {
    id: "appication-for-acquittal-at-any-stage",
    name: "Appication For Acquittal At Any Stage",
    description: "Court-ready template for a(n) appication for acquittal at any stage.",
    fileName: "Appication for acquittal at any stage.docx",
  },
  {
    id: "application-for-additional-evidence",
    name: "Application For Additional Evidence",
    description: "Court-ready template for a(n) application for additional evidence.",
    fileName: "Application for Additional Evidence.docx",
  },
  {
    id: "complaint-under-section-200-cr-p-c",
    name: "Complaint Under Section 200 Cr.P.C.",
    description: "Court-ready template for a(n) complaint under section 200 cr.p.c..",
    fileName: "COMPLAINT UNDER SECTION 200 Cr.P.C..docx",
  },
  {
    id: "constitutional-petition-for-writ-of-certiorari",
    name: "Constitutional Petition For Writ Of Certiorari",
    description: "Court-ready template for a(n) constitutional petition for writ of certiorari.",
    fileName: "CONSTITUTIONAL PETITION FOR WRIT OF CERTIORARI.docx",
  },
  {
    id: "constitutional-petition-for-writ-of-mandamus",
    name: "Constitutional Petition For Writ Of Mandamus",
    description: "Court-ready template for a(n) constitutional petition for writ of mandamus.",
    fileName: "CONSTITUTIONAL PETITION FOR WRIT OF MANDAMUS.docx",
  },
  {
    id: "constitutional-petition-for-writ-of-prohibition",
    name: "Constitutional Petition For Writ Of Prohibition",
    description: "Court-ready template for a(n) constitutional petition for writ of prohibition.",
    fileName: "CONSTITUTIONAL PETITION FOR WRIT OF PROHIBITION.docx",
  },
  {
    id: "constitutional-petition-for-writ-of-quo-warranto",
    name: "Constitutional Petition For Writ Of Quo Warranto",
    description: "Court-ready template for a(n) constitutional petition for writ of quo warranto.",
    fileName: "CONSTITUTIONAL PETITION FOR WRIT OF QUO WARRANTO.docx",
  },
  {
    id: "constitutional-petition-under-article-199",
    name: "Constitutional Petition Under Article 199",
    description: "Court-ready template for a(n) constitutional petition under article 199.",
    fileName: "CONSTITUTIONAL PETITION UNDER ARTICLE 199.docx",
  },
  {
    id: "contempt-petition",
    name: "Contempt Petition",
    description: "Court-ready template for a(n) contempt petition.",
    fileName: "CONTEMPT PETITION.docx",
  },
  {
    id: "criminal-appeal-against-the-judgment",
    name: "Criminal Appeal Against The Judgment",
    description: "Court-ready template for a(n) criminal appeal against the judgment.",
    fileName: "CRIMINAL APPEAL AGAINST THE JUDGMENT.docx",
  },
  {
    id: "criminal-miscellaneous-application",
    name: "Criminal Miscellaneous Application",
    description: "Court-ready template for a(n) criminal miscellaneous application.",
    fileName: "CRIMINAL MISCELLANEOUS APPLICATION.docx",
  },
  {
    id: "criminal-revision-petition",
    name: "Criminal Revision Petition",
    description: "Court-ready template for a(n) criminal revision petition.",
    fileName: "CRIMINAL REVISION PETITION.docx",
  },
  {
    id: "execution-petition",
    name: "Execution Petition",
    description: "Court-ready template for a(n) execution petition.",
    fileName: "EXECUTION PETITION.docx",
  },
  {
    id: "habeas-corpus-petition",
    name: "Habeas Corpus Petition",
    description: "Court-ready template for a(n) habeas corpus petition.",
    fileName: "HABEAS CORPUS PETITION.docx",
  },
  {
    id: "joint-application-for-recording-compromise",
    name: "Joint Application For Recording Compromise",
    description: "Court-ready template for a(n) joint application for recording compromise.",
    fileName: "JOINT APPLICATION FOR RECORDING COMPROMISE.docx",
  },
  {
    id: "mercy-petition",
    name: "Mercy Petition",
    description: "Court-ready template for a(n) mercy petition.",
    fileName: "MERCY PETITION.docx",
  },
  {
    id: "petition-for-cancellation-quashment-of-fir",
    name: "Petition For Cancellation - Quashment Of FIR",
    description: "Court-ready template for a(n) petition for cancellation - quashment of fir.",
    fileName: "PETITION FOR CANCELLATION - QUASHMENT OF FIR.docx",
  },
  {
    id: "petition-for-quashment-of-criminal-proceedings",
    name: "Petition For Quashment Of Criminal Proceedings",
    description: "Court-ready template for a(n) petition for quashment of criminal proceedings.",
    fileName: "PETITION FOR QUASHMENT OF CRIMINAL PROCEEDINGS.docx",
  },
  {
    id: "petition-under-section-561-a-cr-p-c",
    name: "Petition Under Section 561-a Cr.P.C.",
    description: "Court-ready template for a(n) petition under section 561-a cr.p.c..",
    fileName: "PETITION UNDER SECTION 561-A Cr.P.C..docx",
  },
  {
    id: "private-criminal-complaint",
    name: "Private Criminal Complaint",
    description: "Court-ready template for a(n) private criminal complaint.",
    fileName: "PRIVATE CRIMINAL COMPLAINT.docx",
  },
  {
    id: "review-petition",
    name: "Review Petition",
    description: "Court-ready template for a(n) review petition.",
    fileName: "REVIEW PETITION.docx",
  },
  {
    id: "transfer-of-case-application",
    name: "Transfer Of Case Application",
    description: "Court-ready template for a(n) transfer of case application.",
    fileName: "Transfer of Case Application.docx",
  },
];

export function getDraftTemplate(id: string): DraftTemplate | undefined {
  return DRAFT_TEMPLATES.find((d) => d.id === id);
}
