// Karachi court names for court-field autocomplete.
export const KARACHI_COURTS: string[] = [
  "District & Sessions Judge - Central",
  "District & Sessions Judge - East",
  "District & Sessions Judge - Malir",
  "District & Sessions Judge - South",
  "District & Sessions Judge - West",
  "I Additional District & Sessions Judge - Central",
  "I Additional District & Sessions Judge - East",
  "I Additional District & Sessions Judge - Malir",
  "I Additional District & Sessions Judge - South",
  "I Additional District & Sessions Judge - West",
  "I Civil Judge & Judicial Magistrate - Central",
  "I Civil Judge & Judicial Magistrate - East",
  "I Civil Judge & Judicial Magistrate - Malir",
  "I Civil Judge & Judicial Magistrate - South",
  "I Civil Judge & Judicial Magistrate - West",
  "I Senior Civil Judge / Assistant Sessions Judge - Central",
  "I Senior Civil Judge / Assistant Sessions Judge - East",
  "I Senior Civil Judge / Assistant Sessions Judge - Malir",
  "I Senior Civil Judge / Assistant Sessions Judge - South",
  "I Senior Civil Judge / Assistant Sessions Judge - West",
  "II Additional District & Sessions Judge - Central",
  "II Additional District & Sessions Judge - East",
  "II Additional District & Sessions Judge - Malir",
  "II Additional District & Sessions Judge - South",
  "II Additional District & Sessions Judge - West",
  "II Civil Judge & Judicial Magistrate - Central",
  "II Civil Judge & Judicial Magistrate - East",
  "II Civil Judge & Judicial Magistrate - Malir",
  "II Civil Judge & Judicial Magistrate - South",
  "II Civil Judge & Judicial Magistrate - West",
  "II Senior Civil Judge / Assistant Sessions Judge - Central",
  "II Senior Civil Judge / Assistant Sessions Judge - East",
  "II Senior Civil Judge / Assistant Sessions Judge - Malir",
  "II Senior Civil Judge / Assistant Sessions Judge - South",
  "II Senior Civil Judge / Assistant Sessions Judge - West",
  "III Additional District & Sessions Judge - Central",
  "III Additional District & Sessions Judge - East",
  "III Additional District & Sessions Judge - Malir",
  "III Additional District & Sessions Judge - South",
  "III Additional District & Sessions Judge - West",
  "III Civil Judge & Judicial Magistrate - Central",
  "III Civil Judge & Judicial Magistrate - East",
  "III Civil Judge & Judicial Magistrate - Malir",
  "III Civil Judge & Judicial Magistrate - South",
  "III Civil Judge & Judicial Magistrate - West",
  "III Senior Civil Judge / Assistant Sessions Judge - Central",
  "III Senior Civil Judge / Assistant Sessions Judge - East",
  "III Senior Civil Judge / Assistant Sessions Judge - Malir",
  "III Senior Civil Judge / Assistant Sessions Judge - South",
  "III Senior Civil Judge / Assistant Sessions Judge - West",
  "IV Additional District & Sessions Judge - Central",
  "IV Additional District & Sessions Judge - East",
  "IV Additional District & Sessions Judge - Malir",
  "IV Additional District & Sessions Judge - South",
  "IV Additional District & Sessions Judge - West",
  "IV Civil Judge & Judicial Magistrate - Central",
  "IV Civil Judge & Judicial Magistrate - East",
  "IV Civil Judge & Judicial Magistrate - Malir",
  "IV Civil Judge & Judicial Magistrate - South",
  "IV Civil Judge & Judicial Magistrate - West",
  "IV Senior Civil Judge / Assistant Sessions Judge - Central",
  "IV Senior Civil Judge / Assistant Sessions Judge - East",
  "IV Senior Civil Judge / Assistant Sessions Judge - Malir",
  "IV Senior Civil Judge / Assistant Sessions Judge - South",
  "IV Senior Civil Judge / Assistant Sessions Judge - West",
  "IX Additional District & Sessions Judge - East",
  "IX Additional District & Sessions Judge - South",
  "IX Additional District & Sessions Judge - West",
  "IX Civil Judge & Judicial Magistrate - Central",
  "IX Civil Judge & Judicial Magistrate - East",
  "IX Civil Judge & Judicial Magistrate - Malir",
  "IX Civil Judge & Judicial Magistrate - South",
  "IX Civil Judge & Judicial Magistrate - West",
  "IX Senior Civil Judge / Assistant Sessions Judge - Central",
  "IX Senior Civil Judge / Assistant Sessions Judge - East",
  "IX Senior Civil Judge / Assistant Sessions Judge - South",
  "IX Senior Civil Judge / Assistant Sessions Judge - West",
  "V Additional District & Sessions Judge - Central",
  "V Additional District & Sessions Judge - East",
  "V Additional District & Sessions Judge - Malir",
  "V Additional District & Sessions Judge - South",
  "V Additional District & Sessions Judge - West",
  "V Civil Judge & Judicial Magistrate - Central",
  "V Civil Judge & Judicial Magistrate - East",
  "V Civil Judge & Judicial Magistrate - Malir",
  "V Civil Judge & Judicial Magistrate - South",
  "V Civil Judge & Judicial Magistrate - West",
  "V Senior Civil Judge / Assistant Sessions Judge - Central",
  "V Senior Civil Judge / Assistant Sessions Judge - East",
  "V Senior Civil Judge / Assistant Sessions Judge - Malir",
  "V Senior Civil Judge / Assistant Sessions Judge - South",
  "V Senior Civil Judge / Assistant Sessions Judge - West",
  "VI Additional District & Sessions Judge - Central",
  "VI Additional District & Sessions Judge - East",
  "VI Additional District & Sessions Judge - Malir",
  "VI Additional District & Sessions Judge - South",
  "VI Additional District & Sessions Judge - West",
  "VI Civil Judge & Judicial Magistrate - Central",
  "VI Civil Judge & Judicial Magistrate - East",
  "VI Civil Judge & Judicial Magistrate - Malir",
  "VI Civil Judge & Judicial Magistrate - South",
  "VI Civil Judge & Judicial Magistrate - West",
  "VI Senior Civil Judge / Assistant Sessions Judge - Central",
  "VI Senior Civil Judge / Assistant Sessions Judge - East",
  "VI Senior Civil Judge / Assistant Sessions Judge - Malir",
  "VI Senior Civil Judge / Assistant Sessions Judge - South",
  "VI Senior Civil Judge / Assistant Sessions Judge - West",
  "VII Additional District & Sessions Judge - Central",
  "VII Additional District & Sessions Judge - East",
  "VII Additional District & Sessions Judge - Malir",
  "VII Additional District & Sessions Judge - South",
  "VII Additional District & Sessions Judge - West",
  "VII Civil Judge & Judicial Magistrate - Central",
  "VII Civil Judge & Judicial Magistrate - East",
  "VII Civil Judge & Judicial Magistrate - Malir",
  "VII Civil Judge & Judicial Magistrate - South",
  "VII Civil Judge & Judicial Magistrate - West",
  "VII Senior Civil Judge / Assistant Sessions Judge - Central",
  "VII Senior Civil Judge / Assistant Sessions Judge - East",
  "VII Senior Civil Judge / Assistant Sessions Judge - South",
  "VII Senior Civil Judge / Assistant Sessions Judge - West",
  "VIII Additional District & Sessions Judge - East",
  "VIII Additional District & Sessions Judge - Malir",
  "VIII Additional District & Sessions Judge - South",
  "VIII Additional District & Sessions Judge - West",
  "VIII Civil Judge & Judicial Magistrate - Central",
  "VIII Civil Judge & Judicial Magistrate - East",
  "VIII Civil Judge & Judicial Magistrate - Malir",
  "VIII Civil Judge & Judicial Magistrate - South",
  "VIII Civil Judge & Judicial Magistrate - West",
  "VIII Senior Civil Judge / Assistant Sessions Judge - Central",
  "VIII Senior Civil Judge / Assistant Sessions Judge - East",
  "VIII Senior Civil Judge / Assistant Sessions Judge - South",
  "VIII Senior Civil Judge / Assistant Sessions Judge - West",
  "X Additional District & Sessions Judge - East",
  "X Additional District & Sessions Judge - South",
  "X Additional District & Sessions Judge - West",
  "X Civil Judge & Judicial Magistrate - Central",
  "X Civil Judge & Judicial Magistrate - East",
  "X Civil Judge & Judicial Magistrate - Malir",
  "X Civil Judge & Judicial Magistrate - South",
  "X Civil Judge & Judicial Magistrate - West",
  "X Senior Civil Judge / Assistant Sessions Judge - Central",
  "X Senior Civil Judge / Assistant Sessions Judge - East",
  "X Senior Civil Judge / Assistant Sessions Judge - South",
  "X Senior Civil Judge / Assistant Sessions Judge - West",
  "XI Additional District & Sessions Judge - East",
  "XI Additional District & Sessions Judge - South",
  "XI Additional District & Sessions Judge - West",
  "XI Civil Judge & Judicial Magistrate - Central",
  "XI Civil Judge & Judicial Magistrate - East",
  "XI Civil Judge & Judicial Magistrate - Malir",
  "XI Civil Judge & Judicial Magistrate - South",
  "XI Civil Judge & Judicial Magistrate - West",
  "XI Senior Civil Judge / Assistant Sessions Judge - Central",
  "XI Senior Civil Judge / Assistant Sessions Judge - East",
  "XI Senior Civil Judge / Assistant Sessions Judge - South",
  "XI Senior Civil Judge / Assistant Sessions Judge - West",
  "XII Additional District & Sessions Judge - East",
  "XII Additional District & Sessions Judge - South",
  "XII Additional District & Sessions Judge - West",
  "XII Civil Judge & Judicial Magistrate - Central",
  "XII Civil Judge & Judicial Magistrate - East",
  "XII Civil Judge & Judicial Magistrate - Malir",
  "XII Civil Judge & Judicial Magistrate - South",
  "XII Civil Judge & Judicial Magistrate - West",
  "XII Senior Civil Judge / Assistant Sessions Judge - Central",
  "XII Senior Civil Judge / Assistant Sessions Judge - East",
  "XII Senior Civil Judge / Assistant Sessions Judge - South",
  "XII Senior Civil Judge / Assistant Sessions Judge - West",
  "XIII Additional District & Sessions Judge - East",
  "XIII Civil Judge & Judicial Magistrate - Central",
  "XIII Civil Judge & Judicial Magistrate - East",
  "XIII Civil Judge & Judicial Magistrate - Malir",
  "XIII Civil Judge & Judicial Magistrate - South",
  "XIII Civil Judge & Judicial Magistrate - West",
  "XIII Senior Civil Judge / Assistant Sessions Judge - East",
  "XIII Senior Civil Judge / Assistant Sessions Judge - South",
  "XIII Senior Civil Judge / Assistant Sessions Judge - West",
  "XIV Additional District & Sessions Judge - East",
  "XIV Civil Judge & Judicial Magistrate - Central",
  "XIV Civil Judge & Judicial Magistrate - East",
  "XIV Civil Judge & Judicial Magistrate - Malir",
  "XIV Civil Judge & Judicial Magistrate - South",
  "XIV Civil Judge & Judicial Magistrate - West",
  "XIV Senior Civil Judge / Assistant Sessions Judge - South",
  "XIV Senior Civil Judge / Assistant Sessions Judge - West",
  "XIX Civil Judge & Judicial Magistrate - Central",
  "XIX Civil Judge & Judicial Magistrate - East",
  "XIX Civil Judge & Judicial Magistrate - South",
  "XIX Civil Judge & Judicial Magistrate - West",
  "XV Civil Judge & Judicial Magistrate - Central",
  "XV Civil Judge & Judicial Magistrate - East",
  "XV Civil Judge & Judicial Magistrate - South",
  "XV Civil Judge & Judicial Magistrate - West",
  "XV Senior Civil Judge / Assistant Sessions Judge - South",
  "XV Senior Civil Judge / Assistant Sessions Judge - West",
  "XVI Civil Judge & Judicial Magistrate - Central",
  "XVI Civil Judge & Judicial Magistrate - East",
  "XVI Civil Judge & Judicial Magistrate - South",
  "XVI Civil Judge & Judicial Magistrate - West",
  "XVI Senior Civil Judge / Assistant Sessions Judge - West",
  "XVII Civil Judge & Judicial Magistrate - Central",
  "XVII Civil Judge & Judicial Magistrate - East",
  "XVII Civil Judge & Judicial Magistrate - South",
  "XVII Civil Judge & Judicial Magistrate - West",
  "XVII Senior Civil Judge / Assistant Sessions Judge - West",
  "XVIII Civil Judge & Judicial Magistrate - Central",
  "XVIII Civil Judge & Judicial Magistrate - East",
  "XVIII Civil Judge & Judicial Magistrate - South",
  "XVIII Civil Judge & Judicial Magistrate - West",
  "XX Civil Judge & Judicial Magistrate - East",
  "XX Civil Judge & Judicial Magistrate - South",
  "XX Civil Judge & Judicial Magistrate - West",
  "XXI Civil Judge & Judicial Magistrate - East",
  "XXI Civil Judge & Judicial Magistrate - South",
  "XXI Civil Judge & Judicial Magistrate - West",
  "XXII Civil Judge & Judicial Magistrate - East",
  "XXII Civil Judge & Judicial Magistrate - South",
  "XXII Civil Judge & Judicial Magistrate - West",
  "XXIII Civil Judge & Judicial Magistrate - East",
  "XXIII Civil Judge & Judicial Magistrate - South",
  "XXIII Civil Judge & Judicial Magistrate - West",
  "XXIV Civil Judge & Judicial Magistrate - East",
  "XXIV Civil Judge & Judicial Magistrate - South",
  "XXIV Civil Judge & Judicial Magistrate - West",
  "XXIX Civil Judge & Judicial Magistrate - East",
  "XXV Civil Judge & Judicial Magistrate - East",
  "XXV Civil Judge & Judicial Magistrate - South",
  "XXV Civil Judge & Judicial Magistrate - West",
  "XXVI Civil Judge & Judicial Magistrate - East",
  "XXVI Civil Judge & Judicial Magistrate - South",
  "XXVI Civil Judge & Judicial Magistrate - West",
  "XXVII Civil Judge & Judicial Magistrate - East",
  "XXVII Civil Judge & Judicial Magistrate - South",
  "XXVIII Civil Judge & Judicial Magistrate - East",
  "XXVIII Civil Judge & Judicial Magistrate - South",
  "XXX Civil Judge & Judicial Magistrate - East",
  "XXXI Civil Judge & Judicial Magistrate - East",
  "XXXII Civil Judge & Judicial Magistrate - East",
  "XXXIII Civil Judge & Judicial Magistrate - East",
  "XXXIV Civil Judge & Judicial Magistrate - East",
  "XXXV Civil Judge & Judicial Magistrate - East"
];
